export const actionNames = {
  ADD_NOTE: 'ADD_NOTE',
  REMOVE_NOTES: 'REMOVE_NOTES',
  MOVE_NOTES: 'MOVE_NOTES',
  CLEAR_NOTES: 'CLEAR_NOTES',
  CHANGE_EDIT_MODE: 'CHANGE_EDIT_MODE',
  SEQUENCER_SETUP: 'SEQUENCER_SETUP'
};
